[package]
name = "cch23-tony"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
base64 = "0.21.5"
serde = "1.0.193"
serde_json = "1.0.108"
shuttle-axum = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.28.2"
tower = "0.4.13"
tracing = "0.1.40"
